// <copyright company="Okta, Inc">
// Copyright (c) 2014-present Okta, Inc. All rights reserved.
// Licensed under the Apache 2.0 license. See the LICENSE file in the project root for full license information.
// </copyright>

/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Template: ModelGeneric
    /// CustomRole
    /// </summary>
    [DataContract(Name = "CustomRole")]
    [JsonConverter(typeof(JsonSubtypes), "Type")]
    [JsonSubtypes.KnownSubType(typeof(CustomRole), "ACCESS_CERTIFICATIONS_ADMIN")]
    [JsonSubtypes.KnownSubType(typeof(CustomRole), "ACCESS_REQUESTS_ADMIN")]
    [JsonSubtypes.KnownSubType(typeof(StandardRole), "API_ACCESS_MANAGEMENT_ADMIN")]
    [JsonSubtypes.KnownSubType(typeof(StandardRole), "APP_ADMIN")]
    [JsonSubtypes.KnownSubType(typeof(CustomRole), "CUSTOM")]
    [JsonSubtypes.KnownSubType(typeof(StandardRole), "GROUP_MEMBERSHIP_ADMIN")]
    [JsonSubtypes.KnownSubType(typeof(StandardRole), "HELP_DESK_ADMIN")]
    [JsonSubtypes.KnownSubType(typeof(StandardRole), "MOBILE_ADMIN")]
    [JsonSubtypes.KnownSubType(typeof(StandardRole), "ORG_ADMIN")]
    [JsonSubtypes.KnownSubType(typeof(StandardRole), "READ_ONLY_ADMIN")]
    [JsonSubtypes.KnownSubType(typeof(StandardRole), "REPORT_ADMIN")]
    [JsonSubtypes.KnownSubType(typeof(StandardRole), "SUPER_ADMIN")]
    [JsonSubtypes.KnownSubType(typeof(StandardRole), "USER_ADMIN")]
    [JsonSubtypes.KnownSubType(typeof(CustomRole), "WORKFLOWS_ADMIN")]
    
    public partial class CustomRole : Role, IEquatable<CustomRole>
    {
        
        /// <summary>
        /// Resource set ID
        /// </summary>
        /// <value>Resource set ID</value>
        [DataMember(Name = "resource-set", EmitDefaultValue = true)]
        public string ResourceSet { get; private set; }

        /// <summary>
        /// Returns false as ResourceSet should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeResourceSet()
        {
            return false;
        }
        /// <summary>
        /// Custom role ID
        /// </summary>
        /// <value>Custom role ID</value>
        [DataMember(Name = "role", EmitDefaultValue = true)]
        public string Role { get; private set; }

        /// <summary>
        /// Returns false as Role should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeRole()
        {
            return false;
        }
        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name = "_links", EmitDefaultValue = true)]
        public LinksCustomRoleResponse Links { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CustomRole {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  ResourceSet: ").Append(ResourceSet).Append("\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CustomRole);
        }

        /// <summary>
        /// Returns true if CustomRole instances are equal
        /// </summary>
        /// <param name="input">Instance of CustomRole to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CustomRole input)
        {
            if (input == null)
            {
                return false;
            }
            return base.Equals(input) && 
                (
                    this.ResourceSet == input.ResourceSet ||
                    (this.ResourceSet != null &&
                    this.ResourceSet.Equals(input.ResourceSet))
                ) && base.Equals(input) && 
                (
                    this.Role == input.Role ||
                    (this.Role != null &&
                    this.Role.Equals(input.Role))
                ) && base.Equals(input) && 
                (
                    this.Links == input.Links ||
                    (this.Links != null &&
                    this.Links.Equals(input.Links))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                
                if (this.ResourceSet != null)
                {
                    hashCode = (hashCode * 59) + this.ResourceSet.GetHashCode();
                }
                if (this.Role != null)
                {
                    hashCode = (hashCode * 59) + this.Role.GetHashCode();
                }
                if (this.Links != null)
                {
                    hashCode = (hashCode * 59) + this.Links.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
