// <copyright company="Okta, Inc">
// Copyright (c) 2014-present Okta, Inc. All rights reserved.
// Licensed under the Apache 2.0 license. See the LICENSE file in the project root for full license information.
// </copyright>

/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Template: ModelGeneric
    /// IdP-specific protocol settings for endpoints, bindings, and algorithms used to connect with the IdP and validate messages
    /// </summary>
    [DataContract(Name = "IdentityProviderProtocol")]
    [JsonConverter(typeof(JsonSubtypes), "Type")]
    [JsonSubtypes.KnownSubType(typeof(ProtocolIdVerification), "ID_PROOFING" == "~" ? null : "ID_PROOFING")]
    [JsonSubtypes.KnownSubType(typeof(ProtocolMtls), "MTLS" == "~" ? null : "MTLS")]
    [JsonSubtypes.KnownSubType(typeof(ProtocolOAuth), "OAUTH2" == "~" ? null : "OAUTH2")]
    [JsonSubtypes.KnownSubType(typeof(ProtocolOidc), "OIDC" == "~" ? null : "OIDC")]
    [JsonSubtypes.KnownSubType(typeof(ProtocolIdVerification), "ProtocolIdVerification" == "~" ? null : "ProtocolIdVerification")]
    [JsonSubtypes.KnownSubType(typeof(ProtocolMtls), "ProtocolMtls" == "~" ? null : "ProtocolMtls")]
    [JsonSubtypes.KnownSubType(typeof(ProtocolOAuth), "ProtocolOAuth" == "~" ? null : "ProtocolOAuth")]
    [JsonSubtypes.KnownSubType(typeof(ProtocolOidc), "ProtocolOidc" == "~" ? null : "ProtocolOidc")]
    [JsonSubtypes.KnownSubType(typeof(ProtocolSaml), "ProtocolSaml" == "~" ? null : "ProtocolSaml")]
    [JsonSubtypes.KnownSubType(typeof(ProtocolSaml), "SAML2" == "~" ? null : "SAML2")]
    
    public partial class IdentityProviderProtocol : IEquatable<IdentityProviderProtocol>
    {

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = true)]
        
        public IdentityProviderProtocolType Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="IdentityProviderProtocol" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public IdentityProviderProtocol() { }
        
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IdentityProviderProtocol {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as IdentityProviderProtocol);
        }

        /// <summary>
        /// Returns true if IdentityProviderProtocol instances are equal
        /// </summary>
        /// <param name="input">Instance of IdentityProviderProtocol to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(IdentityProviderProtocol input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Type == input.Type ||
                    this.Type.Equals(input.Type)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                
                if (this.Type != null)
                {
                    hashCode = (hashCode * 59) + this.Type.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
