// <copyright company="Okta, Inc">
// Copyright (c) 2014-present Okta, Inc. All rights reserved.
// Licensed under the Apache 2.0 license. See the LICENSE file in the project root for full license information.
// </copyright>

/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// The protocol type for the Identity Provider
    /// </summary>
    /// <value>The protocol type for the Identity Provider</value>
    [JsonConverter(typeof(StringEnumSerializingConverter))]
    public sealed class IdentityProviderProtocolType : StringEnum
    {
        /// <summary>
        /// StringEnum IdentityProviderProtocolType for value: ID_PROOFING
        /// </summary>
        public static IdentityProviderProtocolType IDPROOFING = new IdentityProviderProtocolType("ID_PROOFING");
        /// <summary>
        /// StringEnum IdentityProviderProtocolType for value: MTLS
        /// </summary>
        public static IdentityProviderProtocolType MTLS = new IdentityProviderProtocolType("MTLS");
        /// <summary>
        /// StringEnum IdentityProviderProtocolType for value: OAUTH2
        /// </summary>
        public static IdentityProviderProtocolType OAUTH2 = new IdentityProviderProtocolType("OAUTH2");
        /// <summary>
        /// StringEnum IdentityProviderProtocolType for value: OIDC
        /// </summary>
        public static IdentityProviderProtocolType OIDC = new IdentityProviderProtocolType("OIDC");
        /// <summary>
        /// StringEnum IdentityProviderProtocolType for value: SAML2
        /// </summary>
        public static IdentityProviderProtocolType SAML2 = new IdentityProviderProtocolType("SAML2");

        /// <summary>
        /// Implicit operator declaration to accept and convert a string value as a <see cref="IdentityProviderProtocolType"/>
        /// </summary>
        /// <param name="value">The value to use</param>
        public static implicit operator IdentityProviderProtocolType(string value) => new IdentityProviderProtocolType(value);

        /// <summary>
        /// Creates a new <see cref="IdentityProviderProtocolType"/> instance.
        /// </summary>
        /// <param name="value">The value to use.</param>
        public IdentityProviderProtocolType(string value)
            : base(value)
        {
        }
    }


}
