// <copyright company="Okta, Inc">
// Copyright (c) 2014-present Okta, Inc. All rights reserved.
// Licensed under the Apache 2.0 license. See the LICENSE file in the project root for full license information.
// </copyright>

/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Template: ModelGeneric
    /// An EC signing key
    /// </summary>
    [DataContract(Name = "OAuth2ClientJsonWebKeyECResponse")]
    [JsonConverter(typeof(JsonSubtypes), "Kty")]
    [JsonSubtypes.KnownSubType(typeof(OAuth2ClientJsonWebKeyECResponse), "EC" == "~" ? null : "EC")]
    [JsonSubtypes.KnownSubType(typeof(OAuth2ClientJsonWebKeyRsaResponse), "RSA" == "~" ? null : "RSA")]
    
    public partial class OAuth2ClientJsonWebKeyECResponse : OAuth2ClientJsonWebKeyResponseBase, IEquatable<OAuth2ClientJsonWebKeyECResponse>
    {
        /// <summary>
        /// Cryptographic algorithm family for the certificate&#39;s key pair
        /// </summary>
        /// <value>Cryptographic algorithm family for the certificate&#39;s key pair</value>
        [JsonConverter(typeof(StringEnumSerializingConverter))]
        public sealed class KtyEnum : StringEnum
        {
            /// <summary>
            /// StringEnum EC for value: EC
            /// </summary>
            
            public static KtyEnum EC = new KtyEnum("EC");


            /// <summary>
            /// Implicit operator declaration to accept and convert a string value as a <see cref="KtyEnum"/>
            /// </summary>
            /// <param name="value">The value to use</param>
            public static implicit operator KtyEnum(string value) => new KtyEnum(value);

            /// <summary>
            /// Creates a new <see cref="Kty"/> instance.
            /// </summary>
            /// <param name="value">The value to use.</param>
            public KtyEnum(string value)
                : base(value)
            {
            }
        }


        /// <summary>
        /// Cryptographic algorithm family for the certificate&#39;s key pair
        /// </summary>
        /// <value>Cryptographic algorithm family for the certificate&#39;s key pair</value>
        [DataMember(Name = "kty", EmitDefaultValue = true)]
        
        public KtyEnum Kty { get; set; }
        
        /// <summary>
        /// The public x coordinate for the elliptic curve point
        /// </summary>
        /// <value>The public x coordinate for the elliptic curve point</value>
        [DataMember(Name = "x", EmitDefaultValue = true)]
        public string X { get; set; }

        /// <summary>
        /// The public y coordinate for the elliptic curve point
        /// </summary>
        /// <value>The public y coordinate for the elliptic curve point</value>
        [DataMember(Name = "y", EmitDefaultValue = true)]
        public string Y { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OAuth2ClientJsonWebKeyECResponse {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Kty: ").Append(Kty).Append("\n");
            sb.Append("  X: ").Append(X).Append("\n");
            sb.Append("  Y: ").Append(Y).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OAuth2ClientJsonWebKeyECResponse);
        }

        /// <summary>
        /// Returns true if OAuth2ClientJsonWebKeyECResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of OAuth2ClientJsonWebKeyECResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OAuth2ClientJsonWebKeyECResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return base.Equals(input) && 
                (
                    this.Kty == input.Kty ||
                    this.Kty.Equals(input.Kty)
                ) && base.Equals(input) && 
                (
                    this.X == input.X ||
                    (this.X != null &&
                    this.X.Equals(input.X))
                ) && base.Equals(input) && 
                (
                    this.Y == input.Y ||
                    (this.Y != null &&
                    this.Y.Equals(input.Y))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                
                if (this.Kty != null)
                {
                    hashCode = (hashCode * 59) + this.Kty.GetHashCode();
                }
                if (this.X != null)
                {
                    hashCode = (hashCode * 59) + this.X.GetHashCode();
                }
                if (this.Y != null)
                {
                    hashCode = (hashCode * 59) + this.Y.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
