// <copyright company="Okta, Inc">
// Copyright (c) 2014-present Okta, Inc. All rights reserved.
// Licensed under the Apache 2.0 license. See the LICENSE file in the project root for full license information.
// </copyright>

/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Template: ModelGeneric
    /// A [JSON Web Key (JWK)](https://tools.ietf.org/html/rfc7517) is a JSON representation of a cryptographic key used by an OAuth 2.0 client.
    /// </summary>
    [DataContract(Name = "OAuth2ClientJsonWebKeyResponseBase")]
    [JsonConverter(typeof(JsonSubtypes), "Kty")]
    [JsonSubtypes.KnownSubType(typeof(OAuth2ClientJsonWebKeyECResponse), "EC" == "~" ? null : "EC")]
    [JsonSubtypes.KnownSubType(typeof(OAuth2ClientJsonWebKeyECResponse), "OAuth2ClientJsonWebKeyECResponse" == "~" ? null : "OAuth2ClientJsonWebKeyECResponse")]
    [JsonSubtypes.KnownSubType(typeof(OAuth2ClientJsonWebKeyRsaResponse), "OAuth2ClientJsonWebKeyRsaResponse" == "~" ? null : "OAuth2ClientJsonWebKeyRsaResponse")]
    [JsonSubtypes.KnownSubType(typeof(OAuth2ClientJsonWebKeyRsaResponse), "RSA" == "~" ? null : "RSA")]
    
    public partial class OAuth2ClientJsonWebKeyResponseBase : IEquatable<OAuth2ClientJsonWebKeyResponseBase>
    {
        /// <summary>
        /// Cryptographic algorithm family for the certificate&#39;s key pair
        /// </summary>
        /// <value>Cryptographic algorithm family for the certificate&#39;s key pair</value>
        [JsonConverter(typeof(StringEnumSerializingConverter))]
        public sealed class KtyEnum : StringEnum
        {
            /// <summary>
            /// StringEnum RSA for value: RSA
            /// </summary>
            
            public static KtyEnum RSA = new KtyEnum("RSA");

            /// <summary>
            /// StringEnum EC for value: EC
            /// </summary>
            
            public static KtyEnum EC = new KtyEnum("EC");


            /// <summary>
            /// Implicit operator declaration to accept and convert a string value as a <see cref="KtyEnum"/>
            /// </summary>
            /// <param name="value">The value to use</param>
            public static implicit operator KtyEnum(string value) => new KtyEnum(value);

            /// <summary>
            /// Creates a new <see cref="Kty"/> instance.
            /// </summary>
            /// <param name="value">The value to use.</param>
            public KtyEnum(string value)
                : base(value)
            {
            }
        }


        /// <summary>
        /// Cryptographic algorithm family for the certificate&#39;s key pair
        /// </summary>
        /// <value>Cryptographic algorithm family for the certificate&#39;s key pair</value>
        [DataMember(Name = "kty", EmitDefaultValue = true)]
        
        public KtyEnum Kty { get; set; }
        /// <summary>
        /// Status of the OAuth 2.0 client JSON Web Key
        /// </summary>
        /// <value>Status of the OAuth 2.0 client JSON Web Key</value>
        [JsonConverter(typeof(StringEnumSerializingConverter))]
        public sealed class StatusEnum : StringEnum
        {
            /// <summary>
            /// StringEnum ACTIVE for value: ACTIVE
            /// </summary>
            
            public static StatusEnum ACTIVE = new StatusEnum("ACTIVE");

            /// <summary>
            /// StringEnum INACTIVE for value: INACTIVE
            /// </summary>
            
            public static StatusEnum INACTIVE = new StatusEnum("INACTIVE");


            /// <summary>
            /// Implicit operator declaration to accept and convert a string value as a <see cref="StatusEnum"/>
            /// </summary>
            /// <param name="value">The value to use</param>
            public static implicit operator StatusEnum(string value) => new StatusEnum(value);

            /// <summary>
            /// Creates a new <see cref="Status"/> instance.
            /// </summary>
            /// <param name="value">The value to use.</param>
            public StatusEnum(string value)
                : base(value)
            {
            }
        }


        /// <summary>
        /// Status of the OAuth 2.0 client JSON Web Key
        /// </summary>
        /// <value>Status of the OAuth 2.0 client JSON Web Key</value>
        [DataMember(Name = "status", EmitDefaultValue = true)]
        
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Acceptable use of the JSON Web Key
        /// </summary>
        /// <value>Acceptable use of the JSON Web Key</value>
        [JsonConverter(typeof(StringEnumSerializingConverter))]
        public sealed class UseEnum : StringEnum
        {
            /// <summary>
            /// StringEnum Sig for value: sig
            /// </summary>
            
            public static UseEnum Sig = new UseEnum("sig");

            /// <summary>
            /// StringEnum Enc for value: enc
            /// </summary>
            
            public static UseEnum Enc = new UseEnum("enc");


            /// <summary>
            /// Implicit operator declaration to accept and convert a string value as a <see cref="UseEnum"/>
            /// </summary>
            /// <param name="value">The value to use</param>
            public static implicit operator UseEnum(string value) => new UseEnum(value);

            /// <summary>
            /// Creates a new <see cref="Use"/> instance.
            /// </summary>
            /// <param name="value">The value to use.</param>
            public UseEnum(string value)
                : base(value)
            {
            }
        }


        /// <summary>
        /// Acceptable use of the JSON Web Key
        /// </summary>
        /// <value>Acceptable use of the JSON Web Key</value>
        [DataMember(Name = "use", EmitDefaultValue = true)]
        
        public UseEnum Use { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="OAuth2ClientJsonWebKeyResponseBase" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public OAuth2ClientJsonWebKeyResponseBase() { }
        
        /// <summary>
        /// Timestamp when the OAuth 2.0 client JSON Web Key was created
        /// </summary>
        /// <value>Timestamp when the OAuth 2.0 client JSON Web Key was created</value>
        [DataMember(Name = "created", EmitDefaultValue = true)]
        public string Created { get; private set; }

        /// <summary>
        /// Returns false as Created should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCreated()
        {
            return false;
        }
        /// <summary>
        /// The unique ID of the OAuth Client JSON Web Key
        /// </summary>
        /// <value>The unique ID of the OAuth Client JSON Web Key</value>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id { get; private set; }

        /// <summary>
        /// Returns false as Id should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeId()
        {
            return false;
        }
        /// <summary>
        /// Timestamp when the OAuth 2.0 client JSON Web Key was updated
        /// </summary>
        /// <value>Timestamp when the OAuth 2.0 client JSON Web Key was updated</value>
        [DataMember(Name = "lastUpdated", EmitDefaultValue = true)]
        public string LastUpdated { get; private set; }

        /// <summary>
        /// Returns false as LastUpdated should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeLastUpdated()
        {
            return false;
        }
        /// <summary>
        /// Unique identifier of the JSON Web Key in the OAuth 2.0 client&#39;s JWKS
        /// </summary>
        /// <value>Unique identifier of the JSON Web Key in the OAuth 2.0 client&#39;s JWKS</value>
        [DataMember(Name = "kid", EmitDefaultValue = true)]
        public string Kid { get; set; }

        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name = "_links", EmitDefaultValue = true)]
        public OAuthClientSecretLinks Links { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OAuth2ClientJsonWebKeyResponseBase {\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  LastUpdated: ").Append(LastUpdated).Append("\n");
            sb.Append("  Kty: ").Append(Kty).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Kid: ").Append(Kid).Append("\n");
            sb.Append("  Use: ").Append(Use).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OAuth2ClientJsonWebKeyResponseBase);
        }

        /// <summary>
        /// Returns true if OAuth2ClientJsonWebKeyResponseBase instances are equal
        /// </summary>
        /// <param name="input">Instance of OAuth2ClientJsonWebKeyResponseBase to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OAuth2ClientJsonWebKeyResponseBase input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Created == input.Created ||
                    (this.Created != null &&
                    this.Created.Equals(input.Created))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.LastUpdated == input.LastUpdated ||
                    (this.LastUpdated != null &&
                    this.LastUpdated.Equals(input.LastUpdated))
                ) && 
                (
                    this.Kty == input.Kty ||
                    this.Kty.Equals(input.Kty)
                ) && 
                (
                    this.Status == input.Status ||
                    this.Status.Equals(input.Status)
                ) && 
                (
                    this.Kid == input.Kid ||
                    (this.Kid != null &&
                    this.Kid.Equals(input.Kid))
                ) && 
                (
                    this.Use == input.Use ||
                    this.Use.Equals(input.Use)
                ) && 
                (
                    this.Links == input.Links ||
                    (this.Links != null &&
                    this.Links.Equals(input.Links))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                
                if (this.Created != null)
                {
                    hashCode = (hashCode * 59) + this.Created.GetHashCode();
                }
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.LastUpdated != null)
                {
                    hashCode = (hashCode * 59) + this.LastUpdated.GetHashCode();
                }
                if (this.Kty != null)
                {
                    hashCode = (hashCode * 59) + this.Kty.GetHashCode();
                }
                if (this.Status != null)
                {
                    hashCode = (hashCode * 59) + this.Status.GetHashCode();
                }
                if (this.Kid != null)
                {
                    hashCode = (hashCode * 59) + this.Kid.GetHashCode();
                }
                if (this.Use != null)
                {
                    hashCode = (hashCode * 59) + this.Use.GetHashCode();
                }
                if (this.Links != null)
                {
                    hashCode = (hashCode * 59) + this.Links.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
