// <copyright company="Okta, Inc">
// Copyright (c) 2014-present Okta, Inc. All rights reserved.
// Licensed under the Apache 2.0 license. See the LICENSE file in the project root for full license information.
// </copyright>

/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Template: ModelGeneric
    /// Protocol settings for the [SAML 2.0 Authentication Request Protocol](http://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf)
    /// </summary>
    [DataContract(Name = "ProtocolSaml")]
    [JsonConverter(typeof(JsonSubtypes), "Type")]
    [JsonSubtypes.KnownSubType(typeof(ProtocolIdVerification), "ID_PROOFING")]
    [JsonSubtypes.KnownSubType(typeof(ProtocolMtls), "MTLS")]
    [JsonSubtypes.KnownSubType(typeof(ProtocolOAuth), "OAUTH2")]
    [JsonSubtypes.KnownSubType(typeof(ProtocolOidc), "OIDC")]
    [JsonSubtypes.KnownSubType(typeof(ProtocolSaml), "SAML2")]
    
    public partial class ProtocolSaml : IdentityProviderProtocol, IEquatable<ProtocolSaml>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProtocolSaml" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public ProtocolSaml() { }
        
        /// <summary>
        /// Gets or Sets Algorithms
        /// </summary>
        [DataMember(Name = "algorithms", EmitDefaultValue = true)]
        public SamlAlgorithms Algorithms { get; set; }

        /// <summary>
        /// Gets or Sets Credentials
        /// </summary>
        [DataMember(Name = "credentials", EmitDefaultValue = true)]
        public SamlCredentials Credentials { get; set; }

        /// <summary>
        /// Gets or Sets Endpoints
        /// </summary>
        [DataMember(Name = "endpoints", EmitDefaultValue = true)]
        public SamlEndpoints Endpoints { get; set; }

        /// <summary>
        /// Gets or Sets RelayState
        /// </summary>
        [DataMember(Name = "relayState", EmitDefaultValue = true)]
        public SamlRelayState RelayState { get; set; }

        /// <summary>
        /// Gets or Sets Settings
        /// </summary>
        [DataMember(Name = "settings", EmitDefaultValue = true)]
        public SamlSettings Settings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProtocolSaml {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Algorithms: ").Append(Algorithms).Append("\n");
            sb.Append("  Credentials: ").Append(Credentials).Append("\n");
            sb.Append("  Endpoints: ").Append(Endpoints).Append("\n");
            sb.Append("  RelayState: ").Append(RelayState).Append("\n");
            sb.Append("  Settings: ").Append(Settings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProtocolSaml);
        }

        /// <summary>
        /// Returns true if ProtocolSaml instances are equal
        /// </summary>
        /// <param name="input">Instance of ProtocolSaml to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProtocolSaml input)
        {
            if (input == null)
            {
                return false;
            }
            return base.Equals(input) && 
                (
                    this.Algorithms == input.Algorithms ||
                    (this.Algorithms != null &&
                    this.Algorithms.Equals(input.Algorithms))
                ) && base.Equals(input) && 
                (
                    this.Credentials == input.Credentials ||
                    (this.Credentials != null &&
                    this.Credentials.Equals(input.Credentials))
                ) && base.Equals(input) && 
                (
                    this.Endpoints == input.Endpoints ||
                    (this.Endpoints != null &&
                    this.Endpoints.Equals(input.Endpoints))
                ) && base.Equals(input) && 
                (
                    this.RelayState == input.RelayState ||
                    (this.RelayState != null &&
                    this.RelayState.Equals(input.RelayState))
                ) && base.Equals(input) && 
                (
                    this.Settings == input.Settings ||
                    (this.Settings != null &&
                    this.Settings.Equals(input.Settings))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                
                if (this.Algorithms != null)
                {
                    hashCode = (hashCode * 59) + this.Algorithms.GetHashCode();
                }
                if (this.Credentials != null)
                {
                    hashCode = (hashCode * 59) + this.Credentials.GetHashCode();
                }
                if (this.Endpoints != null)
                {
                    hashCode = (hashCode * 59) + this.Endpoints.GetHashCode();
                }
                if (this.RelayState != null)
                {
                    hashCode = (hashCode * 59) + this.RelayState.GetHashCode();
                }
                if (this.Settings != null)
                {
                    hashCode = (hashCode * 59) + this.Settings.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
