// <copyright company="Okta, Inc">
// Copyright (c) 2014-present Okta, Inc. All rights reserved.
// Licensed under the Apache 2.0 license. See the LICENSE file in the project root for full license information.
// </copyright>

/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Template: ModelGeneric
    /// StandardRole
    /// </summary>
    [DataContract(Name = "StandardRole")]
    [JsonConverter(typeof(JsonSubtypes), "Type")]
    [JsonSubtypes.KnownSubType(typeof(CustomRole), "ACCESS_CERTIFICATIONS_ADMIN" == "~" ? null : "ACCESS_CERTIFICATIONS_ADMIN")]
    [JsonSubtypes.KnownSubType(typeof(CustomRole), "ACCESS_REQUESTS_ADMIN" == "~" ? null : "ACCESS_REQUESTS_ADMIN")]
    [JsonSubtypes.KnownSubType(typeof(StandardRole), "API_ACCESS_MANAGEMENT_ADMIN" == "~" ? null : "API_ACCESS_MANAGEMENT_ADMIN")]
    [JsonSubtypes.KnownSubType(typeof(StandardRole), "APP_ADMIN" == "~" ? null : "APP_ADMIN")]
    [JsonSubtypes.KnownSubType(typeof(CustomRole), "CUSTOM" == "~" ? null : "CUSTOM")]
    [JsonSubtypes.KnownSubType(typeof(StandardRole), "GROUP_MEMBERSHIP_ADMIN" == "~" ? null : "GROUP_MEMBERSHIP_ADMIN")]
    [JsonSubtypes.KnownSubType(typeof(StandardRole), "HELP_DESK_ADMIN" == "~" ? null : "HELP_DESK_ADMIN")]
    [JsonSubtypes.KnownSubType(typeof(StandardRole), "MOBILE_ADMIN" == "~" ? null : "MOBILE_ADMIN")]
    [JsonSubtypes.KnownSubType(typeof(StandardRole), "ORG_ADMIN" == "~" ? null : "ORG_ADMIN")]
    [JsonSubtypes.KnownSubType(typeof(StandardRole), "READ_ONLY_ADMIN" == "~" ? null : "READ_ONLY_ADMIN")]
    [JsonSubtypes.KnownSubType(typeof(StandardRole), "REPORT_ADMIN" == "~" ? null : "REPORT_ADMIN")]
    [JsonSubtypes.KnownSubType(typeof(StandardRole), "SUPER_ADMIN" == "~" ? null : "SUPER_ADMIN")]
    [JsonSubtypes.KnownSubType(typeof(StandardRole), "USER_ADMIN" == "~" ? null : "USER_ADMIN")]
    [JsonSubtypes.KnownSubType(typeof(CustomRole), "WORKFLOWS_ADMIN" == "~" ? null : "WORKFLOWS_ADMIN")]
    
    public partial class StandardRole : Role, IEquatable<StandardRole>
    {
        
        /// <summary>
        /// Optional embedded resources for the role assignment
        /// </summary>
        /// <value>Optional embedded resources for the role assignment</value>
        [DataMember(Name = "_embedded", EmitDefaultValue = true)]
        public Object Embedded { get; set; }

        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name = "_links", EmitDefaultValue = true)]
        public LinksAssignee Links { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StandardRole {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Embedded: ").Append(Embedded).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StandardRole);
        }

        /// <summary>
        /// Returns true if StandardRole instances are equal
        /// </summary>
        /// <param name="input">Instance of StandardRole to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StandardRole input)
        {
            if (input == null)
            {
                return false;
            }
            return base.Equals(input) && 
                (
                    this.Embedded == input.Embedded ||
                    (this.Embedded != null &&
                    this.Embedded.Equals(input.Embedded))
                ) && base.Equals(input) && 
                (
                    this.Links == input.Links ||
                    (this.Links != null &&
                    this.Links.Equals(input.Links))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                
                if (this.Embedded != null)
                {
                    hashCode = (hashCode * 59) + this.Embedded.GetHashCode();
                }
                if (this.Links != null)
                {
                    hashCode = (hashCode * 59) + this.Links.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
